@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!include DEVICONS/java_wordmark.puml

AddElementTag("main", $fontColor="#dfffef", $borderColor="#dfffef", $bgColor="#1272de")
AddElementTag("server", $fontColor="#fdae61", $borderColor="#fdae61", $bgColor="#555555")
AddElementTag("client", $fontColor="#ffffcf", $borderColor="#646c5e", $bgColor="#688c4a")
AddElementTag("deprecated", $fontColor="#d73027", $borderColor="#d73027", $bgColor="#444444")

AddElementTag("octagonal", $shape=EightSidedShape(), $legendText="eight sided (восмиугольник) - этих модов может не быть в финальной сборке")

title ИИСн2 Моды (IIAu2 Mods)

Container(test1, "server", $tags="octagonal+server")
Container(test4, "main", $tags="main")
Container(test2, "client", $tags="client")
Container(test3, "deprecated", $tags="deprecated")

Boundary(group_main, "Основа сборки") {
    Container(aeadditions, "AEAdditions", "AEAdditions-1.12.2-1.3.8", $tags="main", $descr="Дополнение для AppliedEnergistics (бывшый ExtraCells2)", $link="https://www.curseforge.com/minecraft/mc-mods/ae-additions-extra-cells-2-fork/files/3814371")
    Container(ae2, "appliedenergistics2", "appliedenergistics2-rv6-stable-7-extended_life-v0.54.20", $tags="main", $descr="Логистический мод", $link="https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life/files/4370127")
    Container(bdlib, "bdlib", "bdlib-1.14.3.12-mc1.12.2", $tags="main", $descr="Depends for Gendustry", $link="https://www.curseforge.com/minecraft/mc-mods/bdlib/files/2518031")
    Container(bc, "buildcraft", "buildcraft-all-7.99.24.8", $tags="octagonal+main", $descr="", $link="https://www.curseforge.com/minecraft/mc-mods/buildcraft/files/3204475")
    Container(chameleon, "Chameleon", "Chameleon-1.12-4.1.3", $tags="main", $descr="Depends for StorageDrawers", $link="https://www.curseforge.com/minecraft/mc-mods/chameleon/files/2450900")
    Container(chickenchunks, "ChickenChunks", "ChickenChunks-1.12.2-2.4.2.74-universal", $tags="main", $descr="Mod with ChunkLoaders", $link="https://www.curseforge.com/minecraft/mc-mods/chicken-chunks-1-8/files/2755785")
    Container(codechickenlib, "CodeChickenLib", "CodeChickenLib-1.12.2-3.2.3.358-universal", $tags="main", $descr="Depends for ChickenChunks", $link="https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8/files/2779848")
    Container(cofhcore, "CoFHCore", "CoFHCore-1.12.2-4.6.6.1-universal", $tags="main", $descr="Depends for many mods", $link="https://www.curseforge.com/minecraft/mc-mods/cofh-core/files/2920433")
    Container(cofhworld, "CoFHWorld", "CoFHWorld-1.12.2-1.4.0.1-universal", $tags="main", $descr="Depends for many mods", $link="https://www.curseforge.com/minecraft/mc-mods/cofh-world/files/2920434")
    Container(computronics, "Computronics", "Computronics-1.12.2-1.6.6", $tags="main", $descr="Дополнение для OpenComputers", $link="https://wiki.vexatos.com/wiki:computronics")
}

Boundary(group_architect, "Архитектурные моды") {
    Container(architecturecraft, "architecturecraft", "architecturecraft-1.12-3.108", $tags="main", $descr="Аналог мода - carpenter", $link="https://www.curseforge.com/minecraft/mc-mods/architecturecraft-tridev/files/4344128")
    Container(bibliocraft, "BiblioCraft", "BiblioCraft[v2.4.6][MC1.12.2]", $tags="main", $descr="Мод с множеством красивых табличек, книжных полок и т.п.", $link="https://www.curseforge.com/minecraft/mc-mods/bibliocraft/files/3647708")
    Container(bonsaitrees, "bonsaitrees", "bonsaitrees-1.1.4-b170", $tags="main", $descr="Мод добавляет красивые мини деревья", $link="https://www.curseforge.com/minecraft/mc-mods/bonsai-trees/files/2846217")
    Container(chisel, "chisel", "Chisel-MC1.12.2-1.0.2.45", $tags="main", $descr="Мод добавляет много разных строительных блоков", $link="https://www.curseforge.com/minecraft/mc-mods/chisel/files/2915375")
}

Boundary(group_interface, "Интерфейсные моды") {
    Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", $descr="Allows users to compare multiple Twitter timelines", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md")
}

Boundary(group_admin, "Моды для администрирования") {
    Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", $descr="Allows users to compare multiple Twitter timelines", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md")
}

Boundary(group_dev, "Моды для настройки сборки") {
    Container(base, "base", "base-1.12.2-3.14.0", $tags="main", $descr="Depends for ContentTweaker", $link="https://www.curseforge.com/minecraft/mc-mods/base/files/3440963")
    Container(contenttweaker, "ContentTweaker", "ContentTweaker-1.12.2-4.10.0", $tags="main", $descr="Addon for CraftTweaker", $link="https://www.curseforge.com/minecraft/mc-mods/contenttweaker/files/3331364")
    Container(crafttweaker, "CraftTweaker2", "CraftTweaker2-1.12-4.1.20.684", $tags="main", $descr="With CraftTweaker you can change recipes, script events, add new commands and even change item properties!", $link="https://www.curseforge.com/minecraft/mc-mods/crafttweaker/files/4379998")
}


Rel(ae2, aeadditions, "")
Rel(codechickenlib, chickenchunks, "")
Rel(cofhworld, cofhcore, "")
Rel(base, contenttweaker, "")
Rel(crafttweaker, contenttweaker, "")


'Lay_D(group_main, group_architect)
'Lay_D(group_architect, group_interface)
'Lay_D(group_interface, group_admin)
'Lay_D(group_admin, group_dev)


SHOW_LEGEND()
@enduml